### ISSUE TITLE
MKS Robin Mini Pinout

### ISSUE THREAD

**Issue by willpuckett** [makerbase-mks/MKS-Robin-mini#3]
Is it possible to include a pins drawing in the documents area of the Robin Mini? 

Something like [this](https://github.com/makerbase-mks/MKS-Robin-Nano-V1.X/blob/master/hardware/MKS%20Robin%20Nano%20V1.2_004/MKS%20Robin%20Nano%20V1.2_004%20PIN.pdf) would be really helpful. 

Cheers,
WP

**Comment by IrishMoss** [comment]
I second this.  I've been a bit shocked that I can't find this anywhere.  All my googling for the robin mini pinouts, and all i can find is info on the nano.

**Comment by jlucm2a** [comment]
I confirm, impossible to find any pinout for this card, it's a shame.

**Comment by willpuckett** [comment]
It's mostly the same as the the MKS Nano...

If you look at the [pinout drawing for the nano](https://github.com/makerbase-mks/MKS-Robin-Nano-V1.X/blob/9372f8a3f39724101d771afe59b8b3a435407c6c/hardware/MKS%20Robin%20Nano%20V1.2_004/MKS%20Robin%20Nano%20V1.2_004%20PIN.pdf), the only pin that differs in the WIFI area is IO0-P13, which according to my intrepretatin of the schematic diagram and testing is `PA8`.

All the SD pins are the same as the Nano.

Fan Pin: PB1 (same as Nano)
PW_DET: PA2 (same as Nano)
PW_OFF: PA3

Using Klipper here with a bunch of fans on the SD card pins, but IMHO I think it would be better to have done them on the Pi with a host MCU because it's causing some difficutly in applying occasional firmware updates FWIW....

**Comment by tjengbudi** [comment]
@willpuckett in the mks robin mini there is reserve interface that located at bottom right. do you know what pin number is that? i also want to used it with klipper. and want to execute it as LED controller

**Comment by willpuckett** [comment]
It looks like pin PB2 (the “Reserved port” is labeled J11). Do be aware that the voltage on that interface is labeled 5v.

Cheers,
WP

**Comment by tjengbudi** [comment]
thanks for your reply, so if i want to used it as led controller. i must
connect it to the relay? but cannot dim the light. right?

**Comment by willpuckett** [comment]
I believe that would depend on your firmware, and the specific LED.... And of course, it is marked "reserved" so it's possible you may encounter difficulty. You can try it, but if you choose to do so be prepared to replace your board if you encounter the unexpected. 

Cheers,
WP
